name: "run tests"
on:
    [push, pull_request, workflow_dispatch]

jobs:
    perl_tester:
        runs-on: ubuntu-latest
        name: "perl v${{ matrix.perl-version }}"

        strategy:
            fail-fast: false
            matrix:
                perl-version:
                    - "5.24"
                    - "5.26"
                    - "5.28"
                    - "5.30"
                    - "5.32"
                    - "5.34"
                    - "5.36"

        container:
            image: perldocker/perl-tester:${{ matrix.perl-version }}

        steps:
            - uses: actions/checkout@v3
            - name: "cpanm --installdeps"
              uses: perl-actions/install-with-cpanm@v1
              with:
                  sudo: false
                  args: "--installdeps --with-develop --notest ."
            - run: perl Makefile.PL
            - run: make test
