name: "run tests (windows)"
on:
    [push, pull_request, workflow_dispatch]

jobs:
    perl_tester:
        runs-on: windows-latest
        name: "strawberry perl"

        steps:
            - uses: actions/checkout@v3
            - run: choco install strawberryperl -y
            - name: "set PATH"
              shell: cmd
              run: '>> %GITHUB_PATH% echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"'
            - name: "cpanm --installdeps"
              uses: perl-actions/install-with-cpanm@v1
              with:
                  sudo: false
                  args: "--installdeps --with-develop --notest ."
            - run: perl Makefile.PL
            - run: gmake test
